name: ci

on:
  push:
    branches: test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: TEST1
        run: |
          ls -lsah
          echo "1>$SSH_USER"
          echo "2>$DOCKERHUB_USERNAME"
          echo "3>$SSH_PASS"
        env:
          SSH_USER: ${{ secrets.NAME1 }}
          SSH_PASS: secretpass